#!/system/bin/sh


# molesarecoming's "brighter" settings
#Setting RGB
color_r=245
color_g=244
color_b=240

echo "$color_r $color_g $color_b" > /sys/devices/platform/kcal_ctrl.0/kcal
echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_ctrl

#Setting gamma
g_white=57  #Whitepoint, LG=0x72, GOOG=0x40,40,20 Low values=extreme whites, risk of blown out highlights 
g_mid=21
g_black=118 #Blackpoint, LG=0x76, GOOG=0x76,76,74 Low values=cut out, banding in the shadows
g_unknown1=0
g_contrast=31  #Contrast,   LG=0x00, GOOG=0x00,00,1F
g_brightness=9   #Brightness, LG=0x00, GOOG=0x00,00,10
g_saturation=72  #Saturation, LG=0x50, GOOG=0x30,30,50
g_unknown2=48
g_unknown3=2   

#Tweak red gamma values here if needed
gr_white=`expr $g_white + 0`
gr_mid=`expr $g_mid + 0`
gr_black=`expr $g_black + 0`
gr_unknown1=`expr $g_unknown1 + 0`
gr_contrast=`expr $g_contrast + 0`
gr_brightness=`expr $g_brightness + 0`
gr_saturation=`expr $g_saturation + 0`
gr_unknown2=`expr $g_unknown2 + 0`
gr_unknown3=`expr $g_unknown3 + 0`
gr_cksummotley=`expr $gr_white + $gr_mid + $gr_black + $gr_unknown1 + $gr_contrast + $gr_brightness + $gr_saturation + $gr_unknown2 + $gr_unknown3`
 
#Tweak green gamma values here if needed
gg_white=`expr $g_white + 0`
gg_mid=`expr $g_mid + 0`
gg_black=`expr $g_black + 0`
gg_unknown1=`expr $g_unknown1 + 0`
gg_contrast=`expr $g_contrast + 0`
gg_brightness=`expr $g_brightness + 0`
gg_saturation=`expr $g_saturation + 0`
gg_unknown2=`expr $g_unknown2 + 0`
gg_unknown3=`expr $g_unknown3 + 0`
gg_cksummotley=`expr $gg_white + $gg_mid + $gg_black + $gg_unknown1 + $gg_contrast + $gg_brightness + $gg_saturation + $gg_unknown2 + $gg_unknown3`

#Tweak blue gamma values here if needed
gb_white=`expr $g_white + 0`
gb_mid=`expr $g_mid + 0`
gb_black=`expr $g_black + 0`
gb_unknown1=`expr $g_unknown1 + 0`
gb_contrast=`expr $g_contrast + 0`
gb_brightness=`expr $g_brightness + 0`
gb_saturation=`expr $g_saturation + 0`
gb_unknown2=`expr $g_unknown2 + 0`
gb_unknown3=`expr $g_unknown3 + 0`
gb_cksummotley=`expr $gb_white + $gb_mid + $gb_black + $gb_unknown1 + $gb_contrast + $gb_brightness + $gb_saturation + $gb_unknown2 + $gb_unknown3`

echo "$gr_cksummotley $gr_white $gr_mid $gr_black $gr_unknown1 $gr_contrast $gr_brightness $gr_saturation $gr_unknown2 $gr_unknown3" > /sys/devices/platform/mipi_lgit.1537/kgamma_r
echo "$gg_cksummotley $gg_white $gg_mid $gg_black $gg_unknown1 $gg_contrast $gg_brightness $gg_saturation $gg_unknown2 $gg_unknown3" > /sys/devices/platform/mipi_lgit.1537/kgamma_g
echo "$gb_cksummotley $gb_white $gb_mid $gb_black $gb_unknown1 $gb_contrast $gb_brightness $gb_saturation $gb_unknown2 $gb_unknown3" > /sys/devices/platform/mipi_lgit.1537/kgamma_b


# Show the current configuration and the checksum
echo "Verify that the values are written correctly..\n"
echo "RGB values:"
cat /sys/devices/platform/kcal_ctrl.0/kcal
echo "\nRed gamma values:"
cat /sys/devices/platform/mipi_lgit.1537/kgamma_r
echo "\nGreen gamma values:"
cat /sys/devices/platform/mipi_lgit.1537/kgamma_g
echo "\nBlue gamma values:"
cat /sys/devices/platform/mipi_lgit.1537/kgamma_b
echo ""

#values tweaked by molesarecoming (Paranoid Android)
#script by jazzboyrules

